[project]
name = "mc2sf"
version = "0.1.0"
description = "A tool that backs up your Minecraft Server to Seafile"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[project.scripts]
mc2sf = "mc2sf.main:main"

[tool.uv.workspace]
members = [
    "mc2sf",
]
