apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appname }}-cm"
  namespace: {{ .Values.namespace }}
data:
  BACKUP_MODE: {{ .Values.mode | quote }}
  SELECTIVE: {{ .Values.selective | quote }}
  SERVER_PATH: {{ .Values.env.server.path | quote }}
  SERVER_NAME: {{ .Values.env.server.name | quote }}
  SERVER_IP: {{ .Values.env.server.ip | quote }}
  SERVER_RCON_PORT: {{ .Values.env.server.rcon_port | quote }}
  SEAFILE_URL: {{ .Values.env.seafile.url | quote }}
  SEAFILE_USERNAME: {{ .Values.env.seafile.username | quote }}
  SEAFILE_UPLOAD_DIR: {{ .Values.env.seafile.dir | quote }}
  DISCORD_WEBHOOK_URL: {{ .Values.env.webhook.discord | quote }}
