apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appname }}-secret"
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SERVER_RCON_PWD: {{ .Values.env.server.rcon_password }}
  SEAFILE_PASSWORD: {{ .Values.env.seafile.password }}
  SEAFILE_REPO_ID: {{ .Values.env.seafile.repoid }}

