# Default values for mc2sf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General Options
namespace: default
appname: mc2sf
image: ghcr.io/cjcocokrisp/mc2sf:latest
imagepullpolicy: Always
cron: "0 0 * * 0" # Every Sunday at midnight
mode: stream # Default mode, other options are single and tar
selective: "true" # Only for tar mode at the moment, if selected will only backup important stuff instead of everything

# Resource Limits
ephemeral_limit: "10Gi"
memory_limit: "4Gi"

# Job Mount Related Options
mountPath: /app/data
mountType: pvc
pvc:
  claimname: mc-server-pvc
nfs:
  server: 127.0.0.1
  path: /

# Configmap & Secret Related Options
env:
  server:
    path: ""
    name: "Minecraft Server"
    ip: "127.0.0.1"
    rcon_port: "25575"
    rcon_password: ""
  seafile:
    url: "127.0.0.1"
    username: "your-username"
    password: "your-super-secret-password"
    dir: ""
    repoid: "your-repo-id"
  webhook:
    discord: ""
